safe: false
lsi: true
baseurl: /hackathon

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "fenced_code_blocks", "autolink"]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"


collections:
  projects:
    output: true
    permalink: /projects/:path/
  roles:
    output: true
    permalink: /roles/:path/



